codebook_config:
  codebook_level: 8
  codebook_vocab: 4096
  feature_dim: 512
  quantizer_path: ''              # set to Stage 1 IU X-Ray checkpoint after training
data_config:
  cand_pool_dir_name: cand_pool/local
  enable_query_instruct: true
  extracted_dir: extracted_embed/BiomedCLIP/cand
  image_size: 224, 224
  in_batch_neg_num: 0
  is_extracted: true
  query_instruct_path: instructions/query_instructions.tsv
  shuffle_cand: false
  test_dir_name: query/test
  train_dir_name: query/train
  val_dir_name: query/val
dataloader_config:
  batch_size: 64
  num_workers: 8
dist_config:
  dist_url: env://
experiment:
  description: ${model.name} ${model.size} ${experiment.instruct_status} ${experiment.exp_name}
  exp_name: InBatch
  instruct_status: Instruct
  path_suffix: ${model.short_name}/${model.size}/${experiment.instruct_status}/${experiment.exp_name}/
model:
  ckpt_config:
    ckpt_dir: checkpoint/GENIUS_biomedclip_iu_xray/Large/Instruct/InBatch
    ckpt_name: ''                 # set to Stage 2 checkpoint filename after training
  gather_embeddings: true
  name: GENIUS_biomedclip_t5small
  short_name: GENIUS_biomedclip
  size: Large
  trie_type: trie_cpp
retrieval_config:
  cand_pools_config:
    cand_pools_name_to_gen_code:
    - iu_xray
    enable_gen_code: true
    gen_code_union_pool: false
  gen_code_dir_name: gen_code
  num_beams: 50
  qrel_dir_name: qrels
  rerank: false
  results_dir_name: retrieval_results
  test_datasets_config:
    correspond_cand_pools_name:
    - iu_xray
    correspond_metrics_name:
    - Recall@1, Recall@5, Recall@10
    correspond_qrels_name:
    - iu_xray
    datasets_name:
    - iu_xray
    enable_gen_code: true
    enable_retrieve: true
  train_datasets_config:
    correspond_cand_pools_name: null
    datasets_name: null
    enable_gen_code: false
    enable_retrieve: false
  use_fp16: true
  val_datasets_config:
    correspond_cand_pools_name: null
    correspond_qrels_name: null
    datasets_name: null
    enable_gen_code: false
    enable_retrieve: false
  write_to_tsv: true
seed: 2023
